// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAwsuaSiA15UJUw2eevQ89ItTkEyw1AG4',
    appId: '1:539752860430:web:4773ff6821b72d0f5fa55f',
    messagingSenderId: '539752860430',
    projectId: 'quranapp-e7105',
    authDomain: 'quranapp-e7105.firebaseapp.com',
    storageBucket: 'quranapp-e7105.appspot.com',
    measurementId: 'G-QCX38C0884',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5CkotVXl3HvHA_mZV9VRjUb0BWF-JRo',
    appId: '1:539752860430:android:5f26916d4d3d45dd5fa55f',
    messagingSenderId: '539752860430',
    projectId: 'quranapp-e7105',
    storageBucket: 'quranapp-e7105.appspot.com',
  );
}
